### ISSUE TITLE
Installation issue with pip

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/date-annotator-example#62] opened 2021-01-25 20:52 UTC
Ran thru a new installation, got past the conda set up of the environment and ran : 

(nlp-sandbox-date-annotator-example) ➜  server git:(develop) pip install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
(nlp-sandbox-date-annotator-example) ➜  server git:(develop) 

This was on a mac 10.15.7 Catalina 

(nlp-sandbox-date-annotator-example) ➜  server git:(develop) which pip
/Users/gkowalsk/opt/miniconda3/envs/nlp-sandbox-date-annotator-example/bin/pip
(nlp-sandbox-date-annotator-example) ➜  server git:(develop)

**Comment by gkowalski** [comment] 2021-01-25 20:53
pip install -r requirements.txt  seems to work better

**Comment by tschaffter** [comment] 2021-01-25 21:29
Is there an issue with the documentation? Otherwise if the issue is resolved, please close the issue.

**Comment by gkowalski** [comment] 2021-01-25 22:34
Yed documentation is incorrect.

**Closed** 2021-01-27 15:12 UTC
Labels: question
